import type { CompanyCardData } from "@/lib/jobs";

/** Mock companies for development/preview so sliders have content to show. */
export const MOCK_COMPANIES: CompanyCardData[] = [
  {
    id: "mock-001",
    company_name: "Sii Sp. z o. o.",
    full_name: null,
    company_website: null,
    company_logo_url: null,
    banner_url: "https://picsum.photos/seed/sii/400/200",
    job_count: 1482,
    recommendations_count: 24,
    location_display: "Warsaw (+19 locations)",
    benefits_count: 5,
  },
  {
    id: "mock-002",
    company_name: "Capgemini Poland",
    full_name: null,
    company_website: null,
    company_logo_url: null,
    banner_url: "https://picsum.photos/seed/capgemini/400/200",
    job_count: 666,
    recommendations_count: 18,
    location_display: "Kraków (+12 locations)",
    benefits_count: 4,
  },
  {
    id: "mock-003",
    company_name: "OEX Cursor SA",
    full_name: null,
    company_website: null,
    company_logo_url: null,
    banner_url: "https://picsum.photos/seed/oex/400/200",
    job_count: 324,
    recommendations_count: 9,
    location_display: "Warsaw (+269 locations)",
    benefits_count: 3,
  },
  {
    id: "mock-004",
    company_name: "Nationale-Nederlanden",
    full_name: null,
    company_website: null,
    company_logo_url: null,
    banner_url: null,
    job_count: 89,
    recommendations_count: 31,
    location_display: "Wrocław (+5 locations)",
    benefits_count: 6,
  },
  {
    id: "mock-005",
    company_name: "AmRest",
    full_name: null,
    company_website: null,
    company_logo_url: null,
    banner_url: "https://picsum.photos/seed/amrest/400/200",
    job_count: 156,
    recommendations_count: 7,
    location_display: "Poznań",
    benefits_count: 2,
  },
  {
    id: "mock-006",
    company_name: "TechFlow Solutions",
    full_name: null,
    company_website: null,
    company_logo_url: null,
    banner_url: null,
    job_count: 42,
    recommendations_count: 15,
    location_display: "Remote (+2 locations)",
    benefits_count: 4,
  },
  {
    id: "mock-007",
    company_name: "DataDrive Inc.",
    full_name: null,
    company_website: null,
    company_logo_url: null,
    banner_url: "https://picsum.photos/seed/datadrive/400/200",
    job_count: 28,
    recommendations_count: 22,
    location_display: "Gdańsk (+1 location)",
    benefits_count: 3,
  },
  {
    id: "mock-008",
    company_name: "CloudNine",
    full_name: null,
    company_website: null,
    company_logo_url: null,
    banner_url: null,
    job_count: 91,
    recommendations_count: 5,
    location_display: "Warsaw",
    benefits_count: 0,
  },
];
